### ISSUE TITLE
How to evaluate the convergent loops and non-convergent loops independently

### ISSUE THREAD

**Issue by Pikachu1010** [ykai16/Lollipop#2]
Do you do the same thing as the whole dataset? Get five times of the neg samples and make sure pos/neg are both convergent or non-convergent and train the classifier?

**Comment by ykai16** [comment]
We evaluated the performance in the cross validation step, i.e the performance for convergent and non-convergent loops in the held-out test data were evaluated. We did not train a separate classifier.
