### ISSUE TITLE
PhastCon feature set...?

### ISSUE THREAD

**Issue by mncfletcher** [ykai16/Lollipop#4]
Hello again - quick question here about the phastCons scores and how they're formatted as features...

From the paper and in the cell line training data you have the "avg_conservation" and "std_conservation" cols.

I'm guessing these values are equivalent to the "phastCon" column in the example CTCF_motifs_p1e-5_with_phastCons.txt ?

I'm confused as to what exactly the PhastCon feature file defined in /media/Data/data/phastCon_raw/ is, and what's the simplest way to generate it.

Any suggestions would be very welcome. Thanks!

**Comment by ykai16** [comment]
Hi,

Currently the "avg_conservation" and "std_conservation" cols are not from the file "CTCF_motifs_p1e-5_with_phastCons.txt", but are from the raw phastCon tracks in .wigFix format (sorry for the confusion). I have made those phastCon tracks available in (https://www.dropbox.com/sh/wpey9xtaztqzvns/AAD29I_6A2m63RcYm-_ujQTca?dl=0). You can simply download these tracks and provide the folder path to Lollipop in the signal table. Please feel free to let me know if you have any trouble when doing this.

Best,
Yan

**Comment by mncfletcher** [comment]
Oh amazing - thanks very much! It just wasn't very clear what exactly the input files were, ahah.
