### ISSUE TITLE
Empty output files?

### ISSUE THREAD

**Issue by mncfletcher** [ykai16/Lollipop#5]
Hi again (ahaha),

I'm running make_denovo_predictions.py with the retrained models for my features; and it runs very happily now.

BUT: um, the saving of the output .bedpe/.bedGraph/.txt files do not work...? As in, I get different #s lines but python just... stops partway through, with no error messages or anything.

e.g. here are examples where the output files are opened by python, and writing begins, but stops at a certain line (output of wc -l)
---
      3 Lollipop_loops.bedpe
      6 Lollipop_loops_cvg.bedgraph
      3 Lollipop_loops.txt
      4 Lollipop_loops_with_features.txt
---

And these files consist of:

---
==> Lollipop_loops.bedpe <==
chr21	9826551	9826569	chr21	9857148	9857166	NA	0.63	.	.	1
chr1	545348	545366	chr1	566409	566427	NA	0.56979367145	.	.	1
chr1	545348	545366	chr1	568880	568898	NA	0.739908842959	.	.	1

==> Lollipop_loops_cvg.bedgraph <==
track type=bedGraph
chr1	0	545348	0.000000
chr1	545348	566409	2.000000
chr1	566409	568880	1.000000
chr21	0	9826551	0.000000
chr21	9826551	9857148	1.000000

==> Lollipop_loops.txt <==
chr21	9826551	9857148	0.63	1
chr1	545348	566409	0.56979367145	1
chr1	545348	568880	0.739908842959	1

==> Lollipop_loops_with_features.txt <==
chrom	anchor1	anchor2	probability	length	motif_pattern	avg_motif_strength	std_motif_strength	avg_conservation	std_conservation	avg_H3K4me3	std_H3K4me3	H3K4me3_in-between	H3K4me3_upstream	H3K4me3_downstream	avg_H3K27ac	std_H3K27ac	H3K27ac_in-between	H3K27ac_upstream	H3K27ac_downstream	avg_H3K9ac	std_H3K9ac	H3K9ac_in-between	H3K9ac_upstreamH3K9ac_downstream	avg_CTCF	std_CTCF	CTCF_in-between	CTCF_upstream	CTCF_downstream
chr21	9826551	9857148	0.63	30597	1	9.2705	9.2705	18.093	15.001	3.38278300702	2.4483460867	1.34773278225	0.380496060525	0.321883617527	3.30327209908	2.42838169593	1.36664622849	0.363723319093	0.320128451006	3.29414884911	2.38306187269	1.36825331132	0.384225363427	0.321244087237	8.14883220396	6.87632145478	1.80591387945	0.614507995708	0.337834461358
chr1	545348	566409	0.56979367145	21061	1	10.58195	10.58195	17.7315	16.8815	0.31249026881	0.00303388610495	0.320372380106	0.303350308689	0.289956788667	0.325279765275	0.0785158054111	0.348303477239	0.364397242877	0.204940361479	0.35019905656	0.0882615508404	0.362297774441	0.375737590746	0.32012894463	6.18902955282	3.60998370288	1.5457243053	0.636873777882	8.55032194366
chr1	545348	568880	0.739908842959	23532	1	10.58195	10.58195	14.4095	13.5595	0.300354724391	0.00910165831486	0.323862055739	0.303350308689	0.32598532019	0.33088803709	0.072907533596	0.338421977622	0.364397242877	0.301299096292	0.338810469355	0.0996501380456	0.349420362152	0.375737590746	0.389353408725	5.13087221861	2.55182636867	2.28679731695	0.636873777882	9.23933552124
---

So I can't see any reason as to why these didn't work...?

For GM12878 and HeLa I get the same issue, but at different line #s.

Do you have any what's causing the issue; or how I might be able to debug? Thanks very much (again)!

**Comment by ykai16** [comment]
Hmm, this is weird...One question here: when you're making de novo predictions, do you use the same signal table as the one you used for training the model?

**Comment by mncfletcher** [comment]
Ummm… no, I don’t think so, let me check? Ahah…

Okay: so for the de novo predictions I use a signal table for my cell line of interest, linking to my cell line’s data, i.e.:

—
$ cat /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/Med211_signal_table_noH3K27me3_20190605.txt
Signal BED Peak
Motif No /icgc/dkfzlsdf/analysis/B060/software/lollipop/Lollipop/data/CTCF_motifs_p1e-5_with_phastCons.txt
PhastCon No /icgc/dkfzlsdf/analysis/B060/software/lollipop/Lollipop/data/phastCon_raw
H3K4me3 /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K4me3.signal.bed /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K4me3_peaks.bed
H3K27ac /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K27ac.signal.bed /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K27ac_peaks.bed
H3K9ac /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K9ac.signal.bed /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_H3K9ac_peaks.bed
CTCF /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_CTCF.signal.bed /icgc/dkfzlsdf/analysis/B060/gfi1b_herbst/TAD_prediction_lollipop/fixed_input_files_Med211/Med211_CTCF_peaks.bed
—

And for the model training: I edited the signal tables that you included with Lollipop, editing the columns to keep the features that I have for this Med211 cell line in the table above, e.g.:

—
$ cat data/GM12878_training_forMED211_20190603.txt | head -2
chrom start1 start2 response length motif_pattern avg_motif_strength std_motif_strength avg_conservation std_conservation avg_H3K4me3 std_H3K4me3 H3K4me3_in-between H3K4me3_left H3K4me3_right avg_H3K9ac std_H3K9ac H3K9ac_in-between H3K9ac_left H3K9ac_right avg_H3K27ac std_H3K27ac H3K27ac_in-between H3K27ac_left H3K27ac_right avg_CTCF std_CTCF CTCF_in-between CTCF_left CTCF_right
chr1 10527 805283 0 794756 1 11.34425 11.34425 3.5135 3.5135 0.0 0.0 64.2502581016 0.0 0.0170497642009 0.0 0.0 0.146133522674 0.0 0.0327093463747 0.0 0.0 0.0556525831281 0.0 0.0 6466.39606233 6460.71564351 65.3014772509 0.0 0.663075762017
—

And make_denovo_predictions.py doesn’t throw any error messages at all either - it just dies when writing line X, where line X clearly seems to cause a problem…!




On Jun 13, 2019, at 4:26 PM, ykai16 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, this is weird...One question here: when you're making de novo predictions, do you use the same signal table as the one you used for training the model?

**Comment by ykai16** [comment]
I see. Seems the problem is here: By default, Lollipop considers the features used for training the model are in the same order when it tries to make de novo predictions. So when training and predicting de novo loops are not using the same signals table, Lollipop cannot recognize which feature is which.

To fix it, maybe you can try to make to rows in your signal table as follows: Motif, PhastCon, H3K4me3, H3K9ac, H3K27ac, CTCF

Just let me know if it still not work.

**Comment by mncfletcher** [comment]
Unfortunately changing the order of the rows in the signal table has not made any difference - the output file writing still dies at the same spot... dammit.

Okay... so, let's return to what exactly is needed for the features... cos these are different!

So the header line of the edited feature tables I used for training the 3 models are, as I c+ped above:

---
$ head -1 ../data/GM12878_training_forMED211_20190603.txt
chrom	start1	start2	response	length	motif_pattern	avg_motif_strength	std_motif_strength	avg_conservation	std_conservation	avg_H3K4me3	std_H3K4me3	H3K4me3_in-between	H3K4me3_left	H3K4me3_right	avg_H3K9ac	std_H3K9ac	H3K9ac_in-between	H3K9ac_left	H3K9ac_right	avg_H3K27ac	std_H3K27ac	H3K27ac_in-between	H3K27ac_left	H3K27ac_right	avg_CTCF	std_CTCF	CTCF_in-between	CTCF_left	CTCF_right
---

But if I look at the output files for the de novo predictions I get...

---
$ head -1 Lollipop_loops_with_features.txt
chrom	anchor1	anchor2	probability	length	motif_pattern	avg_motif_strength	std_motif_strength	avg_conservation	std_conservation	avg_H3K4me3	std_H3K4me3	H3K4me3_in-between	H3K4me3_upstream	H3K4me3_downstream	avg_H3K27ac	std_H3K27acH3K27ac_in-between	H3K27ac_upstream	H3K27ac_downstream	avg_H3K9ac	std_H3K9ac	H3K9ac_in-between	H3K9ac_upstream	H3K9ac_downstream	avg_CTCF	std_CTCF	CTCF_in-between	CTCF_upstream	CTCF_downstream
---

... so clearly here the _left and _right features have been renamed _upstream and _downstream. Could that be causing the problem...?

**Comment by ykai16** [comment]
I see. It seems that the features are still not in the same order. By saying same order, I mean the five features generated from H3K9ac(avg_, std_, _in-between, _left, and _right) should come right after the set of H3K4me3 features in the output files of de novo predictions, in order to be the same as that in the training data. 

This is weird, and I will look into it. To quickly solve this problem, could you manually change the order of features in the training data to make it in the same order as in the de novo output files and train a model, and then try to use this model to make predictions?

**Comment by mncfletcher** [comment]
Ah yes, I see what you mean. 

Okay, I've now cut and pasted the columns in the training data so that it matches the de novo output column order above. Will try retraining and then rerunning the predictions...!

**Comment by mncfletcher** [comment]
FYI - I tried it and it sadly stops writing the outputs at a random line, again...!

I really would like to make this work though, ahah ;) I'd be happy to try and bughunt in a more in-depth way, if you could suggest a sensible way of doing so. I'm happy to try to run the code in the de novo prediction script interactively if that might help shed some light on the issue, say?

**Comment by ykai16** [comment]
Hi, would be very glad to help you get though. Could you provide more information on it "stops writing the outputs at a random line"? Did the code finish running and just output very few lines, or did the code just stop there without any error message? Could you paste the running information in terminal?

**Comment by mncfletcher** [comment]
So I don’t have a log, but it goes through the per-chromosome “Reading in reads for CHROM”/etc messages; then after it finishes the processing for the last chromosome, it starts writing the output files and then the code ends without throwing any error messages (or any further messages after the per-chrom processing ones).




On Jun 19, 2019, at 6:01 PM, ykai16 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, would be very glad to help you get though. Could you provide more information on it "stops writing the outputs at a random line"? Did the code finish running and just output very few lines, or did the code just stop there without any error message? Could you paste the running information in terminal?

**Comment by mncfletcher** [comment]
So this is the entire STDOUT when I run the script:

---

$ python ./make_denovo_predictions.py \
>     -b $CTCF_Peaks \
>     -t $information_table \
>     -c $classifier \
>     -o $output_folder

---

Preparing reads information...
Preparing data for chrY...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chrY...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
./make_denovo_predictions.py:94: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  X = data.iloc[:,3:].as_matrix()
Preparing data for chrX...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chrX...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr13...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr13...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr12...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr12...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr11...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr11...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr10...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr10...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr17...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr17...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr16...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr16...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr15...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr15...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr14...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr14...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr19...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr19...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr18...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr18...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr22...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr22...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr20...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr20...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr21...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr21...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr7...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr7...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr6...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr6...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr5...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr5...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr4...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr4...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr3...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr3...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr2...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr2...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr1...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr1...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr9...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr9...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
Preparing data for chr8...
Preparing motif orientation pattern and strength...
Preparing sequence conservation feature...
Read in phastCon in chr8...
Preparing features for H3K4me3...
Preparing features for H3K9ac...
Preparing features for H3K27ac...
Preparing features for CTCF...
$
---

And that's the last line, the next one is a new command line prompt; and the output files still stop at that arbitrary point...

---

$ wc -l *
       9 Lollipop_loops.bedpe
       9 Lollipop_loops.txt
      14 Lollipop_loops_cvg.bedgraph

---

And these files consist of:

---

==> Lollipop_loops.bedpe <==
chr18   97009   97027   chr18   108194  108212  NA      0.53    .       .       1
chr18   97009   97027   chr18   108985  109003  NA      0.53    .       .       1
chr21   9826551 9826569 chr21   9857148 9857166 NA      0.59    .       .       1
chr4    49331751        49331769        chr4    49513608        49513626        NA      0.599854646948  .       .      1
chr4    49331751        49331769        chr4    49515845        49515863        NA      0.719880648817  .       .      1
chr1    545348  545366  chr1    565030  565048  NA      0.969431518785  .       .       1
chr1    545348  545366  chr1    567832  567850  NA      0.68    .       .       1
chr1    545348  545366  chr1    568880  568898  NA      0.67    .       .       1
chr1    545348  545366  chr1    569699  569717  NA      0.65862093478   .       .       1

==> Lollipop_loops.txt <==
chr18   97009   108194  0.53    1
chr18   97009   108985  0.53    1
chr21   9826551 9857148 0.59    1
chr4    49331751        49513608        0.599854646948  1
chr4    49331751        49515845        0.719880648817  1
chr1    545348  565030  0.969431518785  1
chr1    545348  567832  0.68    1
chr1    545348  568880  0.67    1
chr1    545348  569699  0.65862093478   1

==> Lollipop_loops_cvg.bedgraph <==
track type=bedGraph
chr4    0       49331751        0.000000
chr4    49331751        49513608        2.000000
chr4    49513608        49515845        1.000000
chr18   0       97009   0.000000
chr18   97009   108194  2.000000
chr18   108194  108985  1.000000
chr1    0       545348  0.000000
chr1    545348  565030  4.000000
chr1    565030  567832  3.000000
chr1    567832  568880  2.000000
chr1    568880  569699  1.000000
chr21   0       9826551 0.000000
chr21   9826551 9857148 1.000000

---


So... I'm wondering why the ordering of the chroms is so odd (4 at the start?! and it's not even the first chrom processed...?) as well...

**Comment by ykai16** [comment]
From the information above, I think the very limited number of output loops is not caused by any error in the execution of the pipeline. One reason I can speculate is the difference in the input files for feature calculation. It seems that you trained the model from the training data we provided, and the trained model was then applied to the your own data. So if the input files for feature calculation do not follow similar preprocessing for training model and predicting loops,  the features are not comparable in these two tasks,  thus ending up with very few loops.

Here are some detailed information:
In the signal table you used, do you use raw reads after removing redundant reads? We recommend to use SICER (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2732366/) to call peaks, and then use the "island-filtered" reads (i.e reads that located on called peaks, which is an automatic output from SICER) for signal table. Our training data were prepared in this way, because we found that using the island-filtered reads for feature calculation yields better predictions than using all the reads. So it might be important to provide the similarly preprocessed files for making de novo predictions, in order to keep the data for making predictions and data for training models are in comparable (i.e in similar scale).

Detailed information on how to prepare features can be found in the supplementary methods of our paper (https://www.nature.com/articles/s41467-018-06664-6#Sec12). Please let me know if there are any questions.
