### ISSUE TITLE
File format Unmached

### ISSUE THREAD

**Issue by HCMY** [ykai16/Lollipop#6]
Hello! Follow your guidance,  I fined 'CTCF_ChIA-PET_interactions' file for k562 from ENCODE project and its number is ENCLB559JAA, so I used ENCFF001THV.bed.gz, but I find its file format is unmached with 'chrom1 start1 end1 chrom2 start2 end2 IAB FDR strand1 strand2', Plese help~

**Comment by ykai16** [comment]
Hi there,

Thank you for your interest in Lollipop! We have used MICC to process the K562 ChIA-PET data, which can be found in the link attached in the "Generating Training Data" section of Readme. If you want to use the ENCODE file, you can easily manipulate the loops file and set IAB, FDR to a significant number, e.g IAB=10 and FDR=0.01, and strand1=strand2='.'.  Feel free to let me know if you have any additional question.

-Yan

**Comment by HCMY** [comment]
Thank you for your reply !  I'am trying to use CHIA-PET2 which you have mentioned in your paper~, but I wondering  which bridge linker you used?, is that default linker, their default linker is * -A|--linkerA:   one linker sequence, default=GTTGGATAAG
    -B|--linkerB:   the other linker sequence, default=GTTGGAATGT**, thanks a lot!
