### ISSUE TITLE
Gene expression file question

### ISSUE THREAD

**Issue by HCMY** [ykai16/Lollipop#7]
Hi~again, where I can download your gene expression file? It would be kindful if you can provide a download link, Please lol..I am major in Computer Science so I have a lot trouble in bioinformation

**Comment by ykai16** [comment]
Hi,

The gene expression files are uploaded to a dropbox folder: (https://www.dropbox.com/sh/x80fovfyhrgy5c9/AACJkB8yp3j7U22W5D1dim6ma?dl=0)   . Please feel free to let me know if there is any problem downloading the data. Thanks.

**Comment by HCMY** [comment]
Thanks a lot, I've completed runned your program without expression file, your algorithm is amazing, thanks for your contribution!

**Comment by ykai16** [comment]
Glad to hear that! Thanks for your interest in Lollipop,:). So I will close this issue.
